//
//  News.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class News: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _articleId: String?
    var _author: String?
    var _category: String?
    var _content: String?
    var _creationDate: NSNumber?
    var _keywords: Set<String>?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "streaker-mobilehub-1466293945-News"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_articleId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_articleId" : "articleId",
               "_author" : "author",
               "_category" : "category",
               "_content" : "content",
               "_creationDate" : "creationDate",
               "_keywords" : "keywords",
               "_title" : "title",
        ]
    }
}
