//
//  Streaks.h
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//

@import UIKit;
@import AWSDynamoDB;

#import "NoSQLModelHelpers.h"

NS_ASSUME_NONNULL_BEGIN


@interface Streaks : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSNumber *_streakId;
@property (nonatomic, strong) NSNumber *_longest;
@property (nonatomic, strong) NSNumber *_streak;

@end

NS_ASSUME_NONNULL_END
