//
//  Streaks.m
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-objc v0.23
//


#import "Streaks.h"
#import "NoSQLSampleDataGenerator.h"
#import <AWSAuthCore/AWSAuthCore.h>
#import <sys/utsname.h>


@implementation Streaks

+ (NSString *)dynamoDBTableName {

    return @"streaker-mobilehub-1466293945-streaks";
}

+ (NSString *)hashKeyAttribute {

    return @"_streakId";
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
               @"_streakId" : @"streakId",
               @"_longest" : @"longest",
               @"_streak" : @"streak",
             };
}

@end
