//
//  Streaks.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Streaks: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _streakId: NSNumber?
    @objc var _longest: NSNumber?
    @objc var _streak: NSNumber?
    @objc var _trophies: [String]?
    
    class func dynamoDBTableName() -> String {

        return "streaker-mobilehub-1466293945-streaks"
    }
    
    class func hashKeyAttribute() -> String {

        return "_streakId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_streakId" : "streakId",
               "_longest" : "longest",
               "_streak" : "streak",
               "_trophies" : "trophies",
        ]
    }
}
